media:
  input: src/media
  output: /media
content:
  - name: 'videos'
    type: collection
    path: "src/videos"
    label: 'Videos'
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: Subtitle
        type: string
      - name: date
        label: Date
        type: date
      - name: code
        label: Embed code
        type: string
      - name: category
        label: Category
        type: reference
        options:
          collection: categories
  - name: 'categories'
    type: collection
    path: "src/categories"
    label: 'Categories'
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: order
        label: Order
        type: number